-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.AHCM (
  group_identifier text NOT NULL,
  living_situation text,
  housing_problems text,
  food_insecurity_and_transport_issues text,
  utility_shutoff_threat text,
  abuse_physical text,
  abuse_verbal text,
  abuse_threats text,
  abuse_yelling text,
  financial_strain text,
  want_work_help text,
  need_daily_help text,
  feel_lonely text,
  non_english_at_home text,
  want_school_help text,
  exercise_days_per_week bigint,
  exercise_minutes_per_day bigint,
  binge_drinking text,
  tobacco_use text,
  prescription_misuse text,
  illegal_drug_use_count text,
  mental_health_score bigint,
  current_stress text,
  cognitive_difficulty text,
  errand_difficulty text,
  CONSTRAINT AHCM_pkey PRIMARY KEY (group_identifier)
);
CREATE TABLE public.BPS (
  unnamed_0 text,
  group_identifier text NOT NULL,
  assmt_dt text,
  birthdate text,
  age bigint,
  ext_motivation text,
  int_motivation text,
  num_prev_treatments text,
  drugs_of_choice jsonb,
  drug_craving_score bigint,
  bps_problems bigint,
  bps_medical text,
  bps_employment bigint,
  bps_peer_support bigint,
  bps_drug_alcohol bigint,
  bps_legal text,
  bps_family bigint,
  bps_mh bigint,
  bps_total bigint,
  CONSTRAINT BPS_pkey PRIMARY KEY (group_identifier)
);
CREATE TABLE public.DERS (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  ders_q1_clear_feelings bigint,
  ders_q10_acknowledge bigint,
  ders_q11_angry_self bigint,
  ders_q12_embarrassed bigint,
  ders_q13_work_difficulty bigint,
  ders_q14_out_control bigint,
  ders_q15_remain_upset bigint,
  ders_q16_end_depressed bigint,
  ders_q17_valid_important bigint,
  ders_q18_focus_difficulty bigint,
  ders_q19_feel_out_control bigint,
  ders_q2_pay_attention bigint,
  ders_q20_get_things_done bigint,
  ders_q21_ashamed bigint,
  ders_q22_find_way_better bigint,
  ders_q23_feel_weak bigint,
  ders_q24_control_behaviors bigint,
  ders_q25_feel_guilty bigint,
  ders_q26_concentrate_difficulty bigint,
  ders_q27_control_difficulty bigint,
  ders_q28_nothing_to_do bigint,
  ders_q29_irritated_self bigint,
  ders_q3_overwhelming bigint,
  ders_q30_feel_bad_self bigint,
  ders_q31_wallowing bigint,
  ders_q32_lose_control bigint,
  ders_q33_think_difficulty bigint,
  ders_q34_figure_out bigint,
  ders_q35_long_time_better bigint,
  ders_q36_emotions_overwhelming bigint,
  ders_q4_no_idea bigint,
  ders_q5_difficulty_sense bigint,
  ders_q6_attentive bigint,
  ders_q7_know_exactly bigint,
  ders_q8_care_about bigint,
  ders_q9_confused bigint,
  CONSTRAINT DERS_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.DERS_2 (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  ders2_q1_clear_feelings bigint,
  ders2_q10_acknowledge bigint,
  ders2_q11_angry_self bigint,
  ders2_q12_embarrassed bigint,
  ders2_q13_work_difficulty bigint,
  ders2_q14_out_control bigint,
  ders2_q15_remain_upset bigint,
  ders2_q16_end_depressed bigint,
  ders2_q17_valid_important bigint,
  ders2_q18_focus_difficulty bigint,
  ders2_q19_feel_out_control bigint,
  ders2_q2_pay_attention bigint,
  ders2_q20_get_things_done bigint,
  ders2_q21_ashamed bigint,
  ders2_q22_find_way_better bigint,
  ders2_q23_feel_weak bigint,
  ders2_q24_control_behaviors bigint,
  ders2_q25_feel_guilty bigint,
  ders2_q26_concentrate_difficulty bigint,
  ders2_q27_control_difficulty bigint,
  ders2_q28_nothing_to_do bigint,
  ders2_q29_irritated_self bigint,
  ders2_q3_overwhelming bigint,
  ders2_q30_feel_bad_self bigint,
  ders2_q31_wallowing bigint,
  ders2_q32_lose_control bigint,
  ders2_q33_think_difficulty bigint,
  ders2_q34_figure_out bigint,
  ders2_q35_long_time_better bigint,
  ders2_q36_emotions_overwhelming bigint,
  ders2_q4_no_idea bigint,
  ders2_q5_difficulty_sense bigint,
  ders2_q6_attentive bigint,
  ders2_q7_know_exactly bigint,
  ders2_q8_care_about bigint,
  ders2_q9_confused bigint,
  CONSTRAINT DERS_2_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.GAD (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  col_1_feeling_nervous_anxious_or_on_edge bigint,
  col_2_not_being_able_to_stop_or_control_worrying bigint,
  col_3_worrying_too_much_about_different_things bigint,
  col_4_trouble_relaxing bigint,
  col_5_being_so_restless_that_it_is_too_hard_to_sit_still bigint,
  col_5_being_so_restless_that_its_hard_to_sit_still text,
  col_6_becoming_easily_annoyed_or_irritable bigint,
  col_7_feeling_afraid_as_if_something_awful_might_happen bigint,
  CONSTRAINT GAD_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.PHP (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  matched_emotion_words text,
  match_skill_words text,
  match_support_words text,
  craving text,
  pain boolean,
  sad boolean,
  content boolean,
  anger boolean,
  shame boolean,
  fear boolean,
  joy boolean,
  anxiety boolean,
  depressed boolean,
  alone boolean,
  mindfulness_meditation boolean,
  distress_tolerance boolean,
  opposite_action boolean,
  take_my_meds boolean,
  ask_for_help boolean,
  improve_moment boolean,
  parts_work boolean,
  play_the_tape_thru boolean,
  values boolean,
  sleep boolean,
  nutrition boolean,
  exercise boolean,
  fun boolean,
  connection boolean,
  warmth boolean,
  water boolean,
  love boolean,
  therapy boolean,
  CONSTRAINT PHP_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.PHQ (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  col_1_little_interest_or_pleasure_in_doing_things bigint,
  col_10_if_you_checked_off_any_problems_how_difficult_have_these bigint,
  col_2_feeling_down_depressed_or_hopeless bigint,
  col_3_trouble_falling_or_staying_asleep_or_sleeping_too_much bigint,
  col_4_feeling_tired_or_having_little_energy bigint,
  col_5_poor_appetite_or_overeating bigint,
  col_6_feeling_bad_about_yourself_or_that_you_are_failure_or_hav bigint,
  col_7_trouble_concentrating_on_things_such_as_reading_the_newsp bigint,
  col_8_moving_or_speaking_so_slowly_that_other_people_could_have bigint,
  col_9_thoughts_that_you_would_be_better_off_dead_or_of_hurting_ bigint,
  CONSTRAINT PHQ_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.PTSD (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  ptsd_q1_disturbing_memories bigint,
  ptsd_q10_blaming_self_others bigint,
  ptsd_q11_negative_feelings bigint,
  ptsd_q12_loss_interest text,
  ptsd_q13_feeling_distant bigint,
  ptsd_q14_trouble_positive_feelings bigint,
  ptsd_q15_irritable_behavior bigint,
  ptsd_q16_risky_behavior bigint,
  ptsd_q17_hypervigilant bigint,
  ptsd_q18_easily_startled bigint,
  ptsd_q19_concentration_difficulty bigint,
  ptsd_q2_disturbing_dreams bigint,
  ptsd_q20_sleep_trouble bigint,
  ptsd_q3_reliving_experience text,
  ptsd_q4_upset_reminders bigint,
  ptsd_q5_physical_reactions bigint,
  ptsd_q6_avoiding_memories bigint,
  ptsd_q7_avoiding_reminders bigint,
  ptsd_q8_memory_trouble bigint,
  ptsd_q9_negative_beliefs bigint,
  CONSTRAINT PTSD_pkey PRIMARY KEY (unique_id)
);
CREATE TABLE public.Patient Intake History (
  group_identifier text NOT NULL,
  initial_group_identifier text,
  mult_patient boolean,
  admission_dt text,
  discharge_dt text,
  status text,
  referrer text,
  discharge_type text,
  social_risk_screen bigint,
  nutrition_screen bigint,
  pain_score bigint,
  trauma_assmt text,
  bps_assmt_problems bigint,
  bps_assmt_medical bigint,
  bps_assmt_employment bigint,
  bps_assmt_peer bigint,
  bps_drug_alcohol bigint,
  bps_legal text,
  bps_family bigint,
  bps_mental_health bigint,
  bps_total bigint,
  ahcm_avg_phys_days bigint,
  ahcm_avg_phys_minutes bigint,
  ahcm_safety_total bigint,
  ahcm_mental_total text,
  CONSTRAINT Patient Intake History_pkey PRIMARY KEY (group_identifier)
);
CREATE TABLE public.Patient Substance History (
  group_identifier text NOT NULL,
  substance text NOT NULL,
  use_flag bigint,
  pattern_of_use text,
  pattern_of_use_consolidated text,
  CONSTRAINT Patient Substance History_pkey PRIMARY KEY (group_identifier, substance)
);
CREATE TABLE public.STATS TEST (
  group_identifier text NOT NULL,
  who bigint,
  gad bigint,
  phq bigint,
  pcl bigint,
  ders bigint,
  status text,
  discharge_type text,
  admission_dt text,
  discharge_dt text,
  program text,
  CONSTRAINT STATS TEST_pkey PRIMARY KEY (group_identifier)
);
CREATE TABLE public.WHO (
  unique_id text NOT NULL,
  group_identifier text,
  assessment_date text,
  col_1_i_have_felt_cheerful_in_good_spirits bigint,
  col_2_i_have_felt_calm_and_relaxed bigint,
  col_3_i_have_felt_active_and_vigorous bigint,
  col_4_i_woke_up_feeling_fresh_and_rested text,
  col_5_my_daily_life_has_been_filled_with_things_that_interest_m bigint,
  CONSTRAINT WHO_pkey PRIMARY KEY (unique_id)
); 