version: '3.8'

services:
  healthcare-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: healthcare-mcp-server
    ports:
      - "${MCP_PORT:-8000}:8000"
    environment:
      # MCP Server Configuration
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-healthcare-dashboard}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-1.0.0}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JSON_LOGS=${JSON_LOGS:-true}
    
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: healthcare-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - healthcare-mcp
    profiles:
      - production
    restart: unless-stopped

# Optional: Add persistent volume for logs
volumes:
  mcp_logs:
    driver: local

# Network configuration
networks:
  default:
    name: healthcare-mcp-network
    driver: bridge